"""create_jobs_table

Revision ID: 36ea141c203e
Revises: aa0703203d70
Create Date: 2026-05-26 00:03:40.913659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ea141c203e'
down_revision: Union[str, None] = 'aa0703203d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.Enum('wishlist', 'applied', 'phone_screen', 'onsite', 'offer', name='jobstage'), server_default='wishlist', nullable=False),
    sa.Column('outcome', sa.Enum('active', 'frozen', 'rejected', 'withdrawn', 'accepted', name='joboutcome'), server_default='active', nullable=False),
    sa.Column('job_url', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_tenant', 'jobs', ['tenant_id'], unique=False)
    op.create_index('idx_jobs_tenant_cursor', 'jobs', ['tenant_id', 'applied_date', 'id'], unique=False)
    op.create_index('idx_jobs_tenant_stage_outcome', 'jobs', ['tenant_id', 'stage', 'outcome'], unique=False)
    op.create_index(op.f('ix_jobs_deleted_at'), 'jobs', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_deleted_at'), table_name='jobs')
    op.drop_index('idx_jobs_tenant_stage_outcome', table_name='jobs')
    op.drop_index('idx_jobs_tenant_cursor', table_name='jobs')
    op.drop_index('idx_jobs_tenant', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
